[build]
  base = "frontend"
  command = "npm --prefix ../backend install && npm --prefix ../backend run build && npm run build"
  publish = "dist"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
